version: '3.8'

services:
  keycloak:
    build:
      context: ./keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
    container_name: broker
    depends_on:
      - keycloak
    environment:
      BROKER_PORT: "8081"
      OIDC_ISSUER: "http://keycloak:8080/realms/agent-identity-poc"
      BROKER_SIGNING_SECRET: "mysecret"
      STORAGE_PATH: "/data/agents.json"
    volumes:
      - ./data:/data
    ports:
      - "8081:8081"

  agent_runner:
    build:
      context: .
      dockerfile: agent_runner/Dockerfile
    container_name: agent_runner
    depends_on:
      - broker
    command: ["/usr/local/bin/agent_runner"]
